spring:
  application:
    name: "fahasa-backend"
  datasource:
    url: "jdbc:postgresql://localhost:5432/fahasa"
    username: "postgres"
    password: "admin"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        one-indexed-parameters: true

  # config mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: tocanhvan079@gmail.com
    password: aopjqfbbmbmgsxfo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Logging
logging:
  level:
    org:
      springframework:
        security: TRACE
        orm:
          jpa:
            support: DEBUG
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: trace

#config jwt
jwt:
  base64-secret: aNIcxUXh5vyUE2/kl3rUcwiSRT9kYm0gyZefk1Xsx3iYTEcZZvjc76RIUKxCt6enG1O+fY408f7Af6q5/waEqg==
  access-token-validity-in-seconds: 600
  refresh-token-validity-in-second: 86400