spring:
  application:
    name: "fahasa-backend"
  datasource:
    url: "jdbc:postgresql://localhost:5432/fahasa"
    username: "postgres"
    password: "admin"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        one-indexed-parameters: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: test
          github:
            client-id: test
            client-secret: test
            scope:
              - read:user
              - user:email

  # Config mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: tocanhvan079@gmail.com
    password: aopjqfbbmbmgsxfo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Logging
logging:
  level:
    org:
      springframework:
        security: TRACE
        orm:
          jpa:
            support: DEBUG
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: trace

# Fahasa properties
fahasa:
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: ZjMzMDNkMzMzMzBhNDE5NDZkN2FjNTkxMjE5M2IzMmI1ZThkMDFkNzQzNTNmZDZhYTc0Zjk4Mzg1MmViYTkyYTdmYzI3NDk3NDBhZDU2MzRjNGExYmQyZTg4OGZjMzk1Yzc0M2YwODI5MDJlMWM1Y2EyN2Q3MzY2NmJiODNlNzI=
        token-validity-in-seconds: 1800 # 30 minutes
        token-validity-in-seconds-for-refresh-token: 1_296_000 # 15 days
  mail:
    base-url: http://localhost:8080